/*
 Generated by Sybase Unwired Platform 
 Compiler version - 2.1.3.231
*/ 

#import "MedSalesInventory.h"
#import "MedSalesInventoryMetaData.h"
#import "SUPJsonObject.h"
#import "MedSalesMedSalesDB.h"
#import "SUPEntityDelegate.h"
#import "SUPEntityMetaDataRBS.h"
#import "SUPQuery.h"
#import "MedSalesKeyGenerator.h"
#import "MedSalesLocalKeyGenerator.h"
#import "MedSalesLogRecordImpl.h"

@implementation MedSalesInventory

@synthesize item_id = _item_id;
@synthesize item_name = _item_name;
@synthesize item_price = _item_price;
@synthesize item_organization = _item_organization;
@synthesize surrogateKey = _surrogateKey;

- (int64_t)surrogateKey
{
    return _surrogateKey;
}

- (void)setItem_id:(int32_t)newItem_id
{
    if (newItem_id != self->_item_id)
    {
        self->_item_id = newItem_id;
        self.isDirty = YES;
    }
}

- (void)setItem_name:(NSString*)newItem_name
{
    if (newItem_name != self->_item_name)
    {
		[self->_item_name release];
        self->_item_name = [newItem_name retain];
        self.isDirty = YES;
    }
}

- (void)setItem_price:(float)newItem_price
{
    if (newItem_price != self->_item_price)
    {
        self->_item_price = newItem_price;
        self.isDirty = YES;
    }
}

- (void)setItem_organization:(NSString*)newItem_organization
{
    if (newItem_organization != self->_item_organization)
    {
		[self->_item_organization release];
        self->_item_organization = [newItem_organization retain];
        self.isDirty = YES;
    }
}

- (void)setSurrogateKey:(int64_t)newSurrogateKey
{
    if (newSurrogateKey != self->_surrogateKey)
    {
        self->_surrogateKey = newSurrogateKey;
        self.isNew = YES;
    }
}

static SUPEntityDelegate *g_MedSalesInventory_delegate = nil;

+ (SUPEntityDelegate *) delegate
{
	@synchronized(self) {
		if (g_MedSalesInventory_delegate == nil) {
			g_MedSalesInventory_delegate = [[SUPEntityDelegate alloc] initWithName:@"MedSalesInventory" clazz:[self class]
				metaData:[self metaData] dbDelegate:[MedSalesMedSalesDB delegate] database:[MedSalesMedSalesDB instance]];
		}
	}
	
	return [[g_MedSalesInventory_delegate retain] autorelease];
}

static SUPEntityMetaDataRBS* MedSalesInventory_META_DATA;

+ (SUPEntityMetaDataRBS*)metaData
{
    if (MedSalesInventory_META_DATA == nil) {
		MedSalesInventory_META_DATA = [[MedSalesInventoryMetaData alloc] init];
	}
	
	return MedSalesInventory_META_DATA;
}

- (SUPClassMetaDataRBS*)getClassMetaData
{
    return [[self class] metaData];
}

- (void)clearRelationshipObjects
{
}

+ (NSObject<SUPCallbackHandler>*)callbackHandler
{
	return [[self delegate] callbackHandler];
}

+ (void)registerCallbackHandler:(NSObject<SUPCallbackHandler>*)newCallbackHandler
{
	[[self delegate] registerCallbackHandler:newCallbackHandler];
}
- (id) init
{
    if ((self = [super init]))
    {
        self.classMetaData = [MedSalesInventory metaData];
        [self setEntityDelegate:(SUPEntityDelegate*)[MedSalesInventory delegate]];
    }
    return self;    
}

- (void)dealloc
{
    if(_item_name)
    {
        [_item_name release];
        _item_name = nil;
    }
    if(_item_organization)
    {
        [_item_organization release];
        _item_organization = nil;
    }
	[super dealloc];
}




+ (MedSalesInventory*)find:(int64_t)id_
{
    SUPObjectList *keys = [SUPObjectList getInstance];
    [keys add:[NSNumber numberWithLong:id_]];
    return (MedSalesInventory*)[(SUPEntityDelegate*)([[self class] delegate]) findEntityWithKeys:keys];
}

+ (SUPObjectList*)findWithQuery:(SUPQuery*)query
{
    return (SUPObjectList*)[(SUPEntityDelegate*)([[self class] delegate])  findWithQuery:query:[MedSalesInventory class]];
}

- (int64_t)_pk
{
    return (int64_t)[[self i_pk] longValue];
}

+ (MedSalesInventory*)load:(int64_t)id_
{
    return (MedSalesInventory*)[(SUPEntityDelegate*)([[self class] delegate]) load:[NSNumber numberWithLong:id_]];
}

+ (MedSalesInventory*)getInstance
{
    MedSalesInventory* me = [[MedSalesInventory alloc] init];
    [me autorelease];
    return me;
}
- (SUPString)getLastOperation
{
    if (self.pendingChange == 'C')
    {
        return @"create";
    }
    else if (self.pendingChange == 'D')
    {
        return @"delete";
    }
    else if (self.pendingChange == 'U')
    {
        return @"update";
    }
    return @"";

}
+ (void)submitPendingOperations
{
    [[[self class] delegate] submitPendingOperations];
}

+ (void)cancelPendingOperations
{
    [[[self class] delegate] cancelPendingOperations];
}
- (MedSalesInventory*)getDownloadState
{
    return (MedSalesInventory*)[self i_getDownloadState];
}

- (MedSalesInventory*) getOriginalState
{
    return (MedSalesInventory*)[self i_getOriginalState];
}
- (SUPJsonObject*)getAttributeJson:(int)id_
{
    switch(id_)
    {
        default:
        return [super getAttributeJson:id_];
    }

}
- (void)setAttributeJson:(int)id_:(SUPJsonObject*)value
{
    switch(id_)
    { 
        default:
            [super setAttributeJson:id_:value];
            break;
    }

}
- (id)getAttributeLargeObject:(int)id_ loadFromDB:(BOOL)loadFromDB
{
    switch(id_)
    {
        default:
        return [super getAttributeJson:id_];
    }
}
- (void)setAttributeLargeObject:(int)id_:(id)value
{
    switch(id_)
    {
        default:
            [super setAttributeJson:id_:value];
            break;
    }

}

-(SUPFloat) getAttributeFloat:(int)id_
{
    switch(id_)
    {
    case 328:
        return self.item_price;
    default:
         return [super getAttributeFloat:id_];
    }
}

-(void) setAttributeFloat:(int)id_:(SUPFloat)v
{
    switch(id_)
    {
    case 328:
        self.item_price = v;
        break;;
    default:
        [super setAttributeFloat:id_:v];
        break;;
    }
}
-(SUPLong) getAttributeLong:(int)id_
{
    switch(id_)
    {
    case 330:
        return self.surrogateKey;
    default:
         return [super getAttributeLong:id_];
    }
}

-(void) setAttributeLong:(int)id_:(SUPLong)v
{
    switch(id_)
    {
    case 330:
        self.surrogateKey = v;
        break;;
    default:
        [super setAttributeLong:id_:v];
        break;;
    }
}
-(SUPString) getAttributeString:(int)id_
{
    switch(id_)
    {
    case 327:
        return self.item_name;
    case 329:
        return self.item_organization;
    default:
         return [super getAttributeString:id_];
    }
}

-(void) setAttributeString:(int)id_:(SUPString)v
{
    switch(id_)
    {
    case 327:
        self.item_name = v;
        break;;
    case 329:
        self.item_organization = v;
        break;;
    default:
        [super setAttributeString:id_:v];
        break;;
    }
}
-(SUPInt) getAttributeInt:(int)id_
{
    switch(id_)
    {
    case 326:
        return self.item_id;
    default:
         return [super getAttributeInt:id_];
    }
}

-(void) setAttributeInt:(int)id_:(SUPInt)v
{
    switch(id_)
    {
    case 326:
        self.item_id = v;
        break;;
    default:
        [super setAttributeInt:id_:v];
        break;;
    }
}
- (SUPObjectList*)getLogRecords
{
   return [MedSalesLogRecordImpl findByEntity:@"Inventory":[self keyToString]];
}




- (NSString*)toString
{
	NSString* str = [NSString stringWithFormat:@"\
	Inventory = \n\
	    item_id = %i,\n\
	    item_name = %@,\n\
	    item_price = %f,\n\
	    item_organization = %@,\n\
	    pending = %i,\n\
	    pendingChange = %c,\n\
	    replayPending = %qi,\n\
	    replayFailure = %qi,\n\
	    surrogateKey = %qi,\n\
	    replayCounter = %qi,\n\
	    disableSubmit = %i,\n\
	    isNew = %i,\n\
        isDirty = %i,\n\
        isDeleted = %i,\n\
	\n"
    	,self.item_id
    	,self.item_name
    	,self.item_price
    	,self.item_organization
    	,self.pending
    	,self.pendingChange
    	,self.replayPending
    	,self.replayFailure
    	,self.surrogateKey
    	,self.replayCounter
    	,self.disableSubmit
		,self.isNew
		,self.isDirty
		,self.isDeleted
	];
	return str;

}

- (NSString*)description
{
	return [self toString];
}
+ (SUPObjectList*)getPendingObjects
{
    return (SUPObjectList*)[(SUPEntityDelegate*)[[self class] delegate] getPendingObjects];
}

+ (SUPObjectList*)getPendingObjects:(int32_t)skip take:(int32_t)take
{
    return (SUPObjectList*)[(SUPEntityDelegate*)[[self class] delegate] getPendingObjects:skip:take];
}




+ (SUPObjectList*)findAll
{
	return [self findAll:0 take:INT_MAX]; 
}


	

+ (SUPObjectList*)findAll:(int32_t)skip take:(int32_t)take
{
	NSMutableString *sql = nil;
	NSMutableString *_selectSQL = nil;
	_selectSQL = [[[NSMutableString alloc] initWithCapacity:263] autorelease];
	[_selectSQL appendString:@" x.\"a\",x.\"b\",x.\"c\",x.\"d\",x.\"_pf\",x.\"_pc\",x.\"_rp\",x.\"_rf\",x.\"e\",x.\"_rc\",x.\"_ds\" FROM \"medsales_1_0_inventory\" x where (((x.\"_pf\" = 1 or not exists (select x_os.\"e\" from \"medsales_1_0_inventory_os\" x_os where x_os.\"e\" = x.\"e\"))))"];
	sql = [[NSMutableString alloc] initWithFormat:@"select %@", _selectSQL];
	[sql autorelease];
	sql = [[NSMutableString alloc] initWithFormat:@"select %@", _selectSQL];
	[sql autorelease];
	SUPStringList *ids = [SUPStringList listWithCapacity:0];
	SUPObjectList *dts = [SUPObjectList getInstance];
	SUPObjectList* values = [SUPObjectList getInstance];
	return (SUPObjectList*)[[[self class] delegate] findWithSQL:sql withDataTypes:dts withValues:values withIDs:ids withSkip:skip withTake:take withClass:[MedSalesInventory class]];
}



+ (MedSalesInventory*)findByPrimaryKey:(int32_t)item_id
{
	NSMutableString *sql = nil;
	NSMutableString *_selectSQL = nil;
	_selectSQL = [[[NSMutableString alloc] initWithCapacity:288] autorelease];
	[_selectSQL appendString:@"SELECT x.\"a\",x.\"b\",x.\"c\",x.\"d\",x.\"_pf\",x.\"_pc\",x.\"_rp\",x.\"_rf\",x.\"e\",x.\"_rc\",x.\"_ds\" FROM \"medsales_1_0_inventory\" x WHERE (((x.\"_pf\" = 1 or not exists (select x_os.\"e\" from \"medsales_1_0_inventory_os\" x_os where x_os.\"e\" = x.\"e\")))) and ( x.\"a\" = ?)"];
	sql = [[NSMutableString alloc] initWithFormat:@"%@", _selectSQL];
	[sql autorelease];
	SUPStringList *ids = [SUPStringList listWithCapacity:0];
	SUPObjectList *dts = [SUPObjectList getInstance];
	[dts addObject:[SUPDataType forName:@"int"]];
	SUPObjectList* values = [SUPObjectList getInstance];
	[values addObject:[NSNumber numberWithInt:item_id]];
	
	SUPObjectList* res = (SUPObjectList*)[[[self class] delegate] findWithSQL:sql withDataTypes:dts withValues:values withIDs:ids withClass:[MedSalesInventory class]];
	if(res && ([res size] > 0))
	{   
		MedSalesInventory* cus = (MedSalesInventory*)[res item:0];
	    return cus;
	}
	else
	    return nil;
}



+ (SUPObjectList*)findByOrganization:(NSString*)organization
{
	return [self findByOrganization:organization skip:0 take:INT_MAX]; 
}


	

+ (SUPObjectList*)findByOrganization:(NSString*)organization skip:(int32_t)skip take:(int32_t)take
{
	NSMutableString *sql = nil;
	NSMutableString *_selectSQL = nil;
	_selectSQL = [[[NSMutableString alloc] initWithCapacity:282] autorelease];
	[_selectSQL appendString:@" x.\"a\",x.\"b\",x.\"c\",x.\"d\",x.\"_pf\",x.\"_pc\",x.\"_rp\",x.\"_rf\",x.\"e\",x.\"_rc\",x.\"_ds\" FROM \"medsales_1_0_inventory\" x WHERE (((x.\"_pf\" = 1 or not exists (select x_os.\"e\" from \"medsales_1_0_inventory_os\" x_os where x_os.\"e\" = x.\"e\")))) and ( x.\"d\" = ?)"];
	sql = [[NSMutableString alloc] initWithFormat:@"select %@", _selectSQL];
	[sql autorelease];
	SUPStringList *ids = [SUPStringList listWithCapacity:0];
	SUPObjectList *dts = [SUPObjectList getInstance];
	[dts addObject:[SUPDataType forName:@"string"]];
	SUPObjectList* values = [SUPObjectList getInstance];
	[values addObject:organization];
	return (SUPObjectList*)[[[self class] delegate] findWithSQL:sql withDataTypes:dts withValues:values withIDs:ids withSkip:skip withTake:take withClass:[MedSalesInventory class]];
}

/*!
  @method
  @abstract Generated class method 
  @param query
  @throws SUPPersistenceException
 */
+ (int32_t)getSize:(SUPQuery*)query
{
    return [(SUPEntityDelegate*)([[self class] delegate]) getSize:query];
}

@end