/*
 Generated by Sybase Unwired Platform 
 Compiler version - 2.1.3.231
*/ 

#import "MedSalesLocalKeyGeneratorPK.h"
#import "MedSalesLocalKeyGeneratorPKMetaData.h"
#import "SUPJsonObject.h"
#import "MedSalesMedSalesDB.h"
#import "SUPClassDelegate.h"
#import "SUPEntityMetaDataRBS.h"

@implementation MedSalesLocalKeyGeneratorPK

@synthesize remoteId = _remoteId;
@synthesize batchId = _batchId;

static SUPClassDelegate *g_MedSalesLocalKeyGeneratorPK_delegate = nil;

+ (SUPClassDelegate *) delegate
{
	@synchronized(self) {
		if (g_MedSalesLocalKeyGeneratorPK_delegate == nil) {
			g_MedSalesLocalKeyGeneratorPK_delegate = [[SUPClassDelegate alloc] initWithName:@"MedSalesLocalKeyGeneratorPK" clazz:[self class]
				metaData:[self metaData] dbDelegate:[MedSalesMedSalesDB delegate] database:[MedSalesMedSalesDB instance]];
		}
	}
	
	return [[g_MedSalesLocalKeyGeneratorPK_delegate retain] autorelease];
}

static SUPClassMetaDataRBS* MedSalesLocalKeyGeneratorPK_META_DATA;

+ (SUPClassMetaDataRBS*)metaData
{
    if (MedSalesLocalKeyGeneratorPK_META_DATA == nil) {
 	   	MedSalesLocalKeyGeneratorPK_META_DATA = [[MedSalesLocalKeyGeneratorPKMetaData alloc] init];
	}
	
	return MedSalesLocalKeyGeneratorPK_META_DATA;
}

- (SUPClassMetaDataRBS*)getClassMetaData
{
    return [[self class] metaData];
}
- (id) init
{
    if ((self = [super init]))
    {
        self.classMetaData = (SUPEntityMetaDataRBS *)[MedSalesLocalKeyGeneratorPK metaData];
        [self setClassDelegate:[[self class] delegate]];
        
    }
    return self;    
}

-(SUPLong) getAttributeLong:(int)id_
{
    switch(id_)
    {
    case 448:
        return self.batchId;
    default:
        return [super getAttributeLong:id_];
    }
}

-(void) setAttributeLong:(int)id_:(SUPLong)v
{
    switch(id_)
    {
    case 448:
        self.batchId = v;
        break;;
    default:
        [super setAttributeLong:id_:v];
        break;;
    }
}
-(SUPString) getAttributeString:(int)id_
{
    switch(id_)
    {
    case 447:
        return self.remoteId;
    default:
        return [super getAttributeString:id_];
    }
}

-(void) setAttributeString:(int)id_:(SUPString)v
{
    switch(id_)
    {
    case 447:
        self.remoteId = v;
        break;;
    default:
        [super setAttributeString:id_:v];
        break;;
    }
}
+ (MedSalesLocalKeyGeneratorPK*)getInstance
{
    MedSalesLocalKeyGeneratorPK* me = [[MedSalesLocalKeyGeneratorPK alloc] init];
    [me autorelease];
    return me;
}
- (void)dealloc
{
    if(_remoteId)
    {
        [_remoteId release];
        _remoteId = nil;
    }
	[super dealloc];
}

@end