/*
 Generated by Sybase Unwired Platform 
 Compiler version - 2.1.3.231
*/ 

#import "MedSalesLocalKeyGenerator.h"
#import "MedSalesLocalKeyGeneratorMetaData.h"
#import "SUPLocalEntityDelegate.h"
#import "MedSalesMedSalesDB.h"
#import "SUPEntityDelegate.h"
#import "SUPLocalKeyGenerator.h"

@implementation MedSalesLocalKeyGenerator

static SUPLocalEntityDelegate *g_MedSalesLocalKeyGenerator_delegate = nil;

+ (SUPLocalEntityDelegate *) delegate
{
	@synchronized(self) {
		if (g_MedSalesLocalKeyGenerator_delegate == nil) {
			g_MedSalesLocalKeyGenerator_delegate = [[SUPLocalEntityDelegate alloc] initWithName:@"MedSalesLocalKeyGenerator" clazz:[self class]
				metaData:[self metaData] dbDelegate:[MedSalesMedSalesDB delegate] database:[MedSalesMedSalesDB instance]];
		}
	}
	
	return [[g_MedSalesLocalKeyGenerator_delegate retain] autorelease];
}

static SUPEntityMetaDataRBS* MedSalesLocalKeyGenerator_META_DATA;

+ (SUPEntityMetaDataRBS*)metaData
{
    if (MedSalesLocalKeyGenerator_META_DATA == nil) {
 	   	MedSalesLocalKeyGenerator_META_DATA = [[MedSalesLocalKeyGeneratorMetaData alloc] init];
	}
	
	return MedSalesLocalKeyGenerator_META_DATA;
}

- (SUPClassMetaDataRBS*)getClassMetaData
{
    return [[self class] metaData];
}

- (id)init
{
    self = [super initWithParameters:[MedSalesMedSalesDB delegate]:@"co_medsales_1_0_localkeygenerator":100000];
    if (self) {
        // Initialization code here.
        [SUPLocalKeyGenerator setObjectInstance:@"MedSales":self];
    }
    
    return self;
}

+ (MedSalesLocalKeyGenerator*)getInstance
{
    MedSalesLocalKeyGenerator* me = [[MedSalesLocalKeyGenerator alloc] init];
    [me autorelease];
    return me;
}

+ (int64_t)generateId
{
    return [[MedSalesMedSalesDB delegate] generateLocalId];
}

@end