/*
 Generated by Sybase Unwired Platform 
 Compiler version - 2.1.3.231
*/ 

#import "MedSalesKeyPackageName.h"
#import "MedSalesKeyPackageNameMetaData.h"
#import "SUPJsonObject.h"
#import "MedSalesMedSalesDB.h"
#import "SUPClassDelegate.h"
#import "SUPEntityMetaDataRBS.h"

@implementation MedSalesKeyPackageName

@synthesize key_name = _key_name;
@synthesize package_name = _package_name;
@synthesize user_name = _user_name;
@synthesize domain_name = _domain_name;

static SUPClassDelegate *g_MedSalesKeyPackageName_delegate = nil;

+ (SUPClassDelegate *) delegate
{
	@synchronized(self) {
		if (g_MedSalesKeyPackageName_delegate == nil) {
			g_MedSalesKeyPackageName_delegate = [[SUPClassDelegate alloc] initWithName:@"MedSalesKeyPackageName" clazz:[self class]
				metaData:[self metaData] dbDelegate:[MedSalesMedSalesDB delegate] database:[MedSalesMedSalesDB instance]];
		}
	}
	
	return [[g_MedSalesKeyPackageName_delegate retain] autorelease];
}

static SUPClassMetaDataRBS* MedSalesKeyPackageName_META_DATA;

+ (SUPClassMetaDataRBS*)metaData
{
    if (MedSalesKeyPackageName_META_DATA == nil) {
 	   	MedSalesKeyPackageName_META_DATA = [[MedSalesKeyPackageNameMetaData alloc] init];
	}
	
	return MedSalesKeyPackageName_META_DATA;
}

- (SUPClassMetaDataRBS*)getClassMetaData
{
    return [[self class] metaData];
}
- (id) init
{
    if ((self = [super init]))
    {
        self.classMetaData = (SUPEntityMetaDataRBS *)[MedSalesKeyPackageName metaData];
        [self setClassDelegate:[[self class] delegate]];
        
    }
    return self;    
}

-(SUPString) getAttributeString:(int)id_
{
    switch(id_)
    {
    case 410:
        return self.key_name;
    case 412:
        return self.package_name;
    case 411:
        return self.user_name;
    case 413:
        return self.domain_name;
    default:
        return [super getAttributeString:id_];
    }
}

-(void) setAttributeString:(int)id_:(SUPString)v
{
    switch(id_)
    {
    case 410:
        self.key_name = v;
        break;;
    case 412:
        self.package_name = v;
        break;;
    case 411:
        self.user_name = v;
        break;;
    case 413:
        self.domain_name = v;
        break;;
    default:
        [super setAttributeString:id_:v];
        break;;
    }
}
+ (MedSalesKeyPackageName*)getInstance
{
    MedSalesKeyPackageName* me = [[MedSalesKeyPackageName alloc] init];
    [me autorelease];
    return me;
}
- (void)dealloc
{
    if(_key_name)
    {
        [_key_name release];
        _key_name = nil;
    }
    if(_package_name)
    {
        [_package_name release];
        _package_name = nil;
    }
    if(_user_name)
    {
        [_user_name release];
        _user_name = nil;
    }
    if(_domain_name)
    {
        [_domain_name release];
        _domain_name = nil;
    }
	[super dealloc];
}

@end