#import "sybase_sup.h"
#import "SUPLocalKeyGenerator.h"
#import "SUPKeyGeneratorPK.h"
#import "SUPClassWithMetaData.h"

@class SUPEntityMetaDataRBS;
@protocol SUPClassWithMetaData;
@class SUPLocalEntityDelegate;
@class SUPClassMetaDataRBS;
@class MedSalesLocalKeyGeneratorPK;

// public interface declaration, can be used by application.
/*!
 @class MedSalesLocalKeyGenerator
 @abstract This class is part of package "MedSales:1.0"
 @discussion Generated by Sybase Unwired Platform, compiler version 2.1.3.231
*/

@interface MedSalesLocalKeyGenerator : SUPLocalKeyGenerator<SUPClassWithMetaData>
{
}
+ (SUPLocalEntityDelegate *)delegate;
+ (SUPEntityMetaDataRBS*)metaData;
/*!
  @method 
  @abstract Creates a new autoreleased instance of this class
  @discussion
 */
+ (MedSalesLocalKeyGenerator*)getInstance;
- (SUPClassMetaDataRBS*)getClassMetaData;
+ (int64_t) generateId;


@end