/*
 Generated by Sybase Unwired Platform 
 Compiler version - 2.1.3.231
*/ 

#import "MedSalesChangeLogKey.h"
#import "MedSalesChangeLogKeyMetaData.h"
#import "SUPJsonObject.h"
#import "MedSalesMedSalesDB.h"
#import "SUPClassDelegate.h"
#import "SUPEntityMetaDataRBS.h"

@implementation MedSalesChangeLogKey

@synthesize entityType = _entityType;
@synthesize surrogateKey = _surrogateKey;

static SUPClassDelegate *g_MedSalesChangeLogKey_delegate = nil;

+ (SUPClassDelegate *) delegate
{
	@synchronized(self) {
		if (g_MedSalesChangeLogKey_delegate == nil) {
			g_MedSalesChangeLogKey_delegate = [[SUPClassDelegate alloc] initWithName:@"MedSalesChangeLogKey" clazz:[self class]
				metaData:[self metaData] dbDelegate:[MedSalesMedSalesDB delegate] database:[MedSalesMedSalesDB instance]];
		}
	}
	
	return [[g_MedSalesChangeLogKey_delegate retain] autorelease];
}

static SUPClassMetaDataRBS* MedSalesChangeLogKey_META_DATA;

+ (SUPClassMetaDataRBS*)metaData
{
    if (MedSalesChangeLogKey_META_DATA == nil) {
 	   	MedSalesChangeLogKey_META_DATA = [[MedSalesChangeLogKeyMetaData alloc] init];
	}
	
	return MedSalesChangeLogKey_META_DATA;
}

- (SUPClassMetaDataRBS*)getClassMetaData
{
    return [[self class] metaData];
}
- (id) init
{
    if ((self = [super init]))
    {
        self.classMetaData = (SUPEntityMetaDataRBS *)[MedSalesChangeLogKey metaData];
        [self setClassDelegate:[[self class] delegate]];
        
    }
    return self;    
}

-(SUPLong) getAttributeLong:(int)id_
{
    switch(id_)
    {
    case 396:
        return self.surrogateKey;
    default:
        return [super getAttributeLong:id_];
    }
}

-(void) setAttributeLong:(int)id_:(SUPLong)v
{
    switch(id_)
    {
    case 396:
        self.surrogateKey = v;
        break;;
    default:
        [super setAttributeLong:id_:v];
        break;;
    }
}
-(SUPInt) getAttributeInt:(int)id_
{
    switch(id_)
    {
    case 395:
        return self.entityType;
    default:
        return [super getAttributeInt:id_];
    }
}

-(void) setAttributeInt:(int)id_:(SUPInt)v
{
    switch(id_)
    {
    case 395:
        self.entityType = v;
        break;;
    default:
        [super setAttributeInt:id_:v];
        break;;
    }
}
+ (MedSalesChangeLogKey*)getInstance
{
    MedSalesChangeLogKey* me = [[MedSalesChangeLogKey alloc] init];
    [me autorelease];
    return me;
}
- (void)dealloc
{
	[super dealloc];
}

@end