#import "sybase_sup.h"

#import "SUPClassWithMetaData.h"
#import "SUPSISSubscriptionKey.h"


@class SUPClassDelegate;
@class SUPClassMetaDataRBS;

// public interface declaration, can be used by application. 
/*!
 @class MedSalesSISSubscriptionKey
 @abstract This class is part of package "MedSales:1.0"
 @discussion Generated by Sybase Unwired Platform, compiler version 2.1.3.231
*/

@interface MedSalesSISSubscriptionKey : SUPSISSubscriptionKey<SUPClassWithMetaData>
{
}
+ (SUPClassDelegate *)delegate;
+ (SUPClassMetaDataRBS*)metaData;
- (SUPClassMetaDataRBS*)getClassMetaData;


@end