#import "SUPAbstractLogger.h"

/*!
 @class MedSalesLoggerImpl
 @abstract This class is part of package "MedSales:1.0"
 @discussion Generated by Sybase Unwired Platform, compiler version 2.1.3.231
*/ 

@interface MedSalesLoggerImpl: SUPAbstractLogger

@end