#import "sybase_sup.h"
#import "SUPKeyGenerator.h"
#import "SUPKeyGeneratorPK.h"
#import "SUPClassWithMetaData.h"

@class SUPEntityMetaDataRBS;
@protocol SUPClassWithMetaData;
@class SUPEntityDelegate;
@class SUPClassMetaDataRBS;
@class MedSalesKeyGeneratorPK;

// public interface declaration, can be used by application.
/*!
 @class MedSalesKeyGenerator
 @abstract This class is part of package "MedSales:1.0"
 @discussion Generated by Sybase Unwired Platform, compiler version 2.1.3.231
*/

@interface MedSalesKeyGenerator : SUPKeyGenerator<SUPClassWithMetaData>
{
}
+ (SUPEntityDelegate *)delegate;
+ (SUPEntityMetaDataRBS*)metaData;
/*!
  @method 
  @abstract Creates a new autoreleased instance of this class
  @discussion
 */
+ (MedSalesKeyGenerator*)getInstance;
- (SUPClassMetaDataRBS*)getClassMetaData;
+ (int64_t) generateId;


@end